language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.1
addons:
  postgresql: "9.6"
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
sudo: required
dist: trusty
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
notifications:
  recipients:
    - kelostrada@gmail.com
